// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectSparky.Model;

namespace ProjectSparky.Model.Migrations
{
    [DbContext(typeof(ProjectSparyContext))]
    partial class ProjectSparyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065");

            modelBuilder.Entity("ProjectSparky.Model.Alarm", b =>
                {
                    b.Property<string>("AlarmGUID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<DateTime>("AlarmTime");

                    b.Property<string>("AlarmTone");

                    b.HasKey("AlarmGUID");

                    b.ToTable("Alarms");
                });

            modelBuilder.Entity("ProjectSparky.Model.Note", b =>
                {
                    b.Property<string>("NoteGUID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("NoteText");

                    b.HasKey("NoteGUID");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("ProjectSparky.Model.UserAccount", b =>
                {
                    b.Property<string>("UserAccountGUID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccessToken");

                    b.Property<string>("AccountID");

                    b.Property<string>("AccountName");

                    b.Property<string>("RefreshToken");

                    b.Property<DateTime>("TokenExpiresOn");

                    b.HasKey("UserAccountGUID");

                    b.ToTable("UserAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
